### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by sdgandhi** [Alterplay/APOfflineReverseGeocoding#1]
Would the polygon data size be feasible to add city level reverse geocoding?

**Comment by Krivoblotsky** [comment]
Hm, I don't think that this algorithm is flexible enough to add cities info. The initial data file size will be increased with hundreds of times.

The algorithm requires huge update to handle cities. The first thing that comes to mind is to "fetch" the polygons which have centers in some range if the coordinates provided and that search for the city polygon among fetched. I'll think about it.
