### ISSUE TITLE
Country city missing

### ISSUE THREAD

**Issue by m4unot** [Alterplay/APOfflineReverseGeocoding#2]
Hello,
- The city "Odense" in Denmark is not supported. Please support it.

and it would be nice to add city names. Beside that..really well done! really wonderful work :+1: 

is there any plans on porting it to android ?  that would be so good to have on both platform.

**Comment by sarahansen223h** [comment]
I agree ! any update soon regarding this issue???

**Comment by EvgeniyGT** [comment]
Will be fixed in next release.
